### ISSUE TITLE
Update this package. ta-lib already works with python 3.11

### ISSUE THREAD

**Issue by arturdaraujo** [conda-forge/ta-lib-feedstock#22]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Update the package to allow python 3.11

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by agon-shabi** [comment]
Doesn't look this was completed?

Just looking at the files here: https://anaconda.org/conda-forge/ta-lib/files and no mention of py311.
