### ISSUE TITLE
Publish package for python 3.11

### ISSUE THREAD

**Issue by agon-shabi** [conda-forge/ta-lib-feedstock#32]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

`ta-lib` apparently already supports python 3.11, but the highest version supported on conda-forge seems to be python 3.10.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by sanurielf** [comment]
3.11 should be available with latest builds.
